### ISSUE TITLE
No module named skbuild while building docker

### ISSUE THREAD

**Issue by Praj390** [jdgalviss/autonomous_mobile_robot#2]
![image](https://user-images.githubusercontent.com/57248801/108431452-e27fc680-7210-11eb-809d-44d9e6be9513.png)

I am getting this error while building docker. I am new to the docker and unable to resolve it. Could you tell me what is wrong?

**Comment by jdgalviss** [comment]
I just merged a pull-request that fixes this issue. (Check pull request #3). Apparently, newer versions of opencv can't be installed by an older version of pip. Hence, adding `pip3 install --upgrade pip` before `pip3 install -r requirements.txt` fixes the issue.
