### ISSUE TITLE
Missing folder vision/semseg

### ISSUE THREAD

**Issue by phamngocninh** [jdgalviss/autonomous_mobile_robot#7]
I am interested in your project. But there are some folders missing, like vision/semseg , can you please add it. Thanks very much!

**Comment by jdgalviss** [comment]
Hi. Yes, sorry I haven't had time to clean the code and add it. In the mean time, the branch "dwa" is stable. It does not have exactly the same components, but it has some similarities. I will fix this as soon as I can.

**Comment by phamngocninh** [comment]
Thank you! But I have some doubts about costmap. Can you give me the theoretical background about cost_center,obstacle cost map,cost_forward,Total cost. My email is phamngocninh.bk@gmail.com
